Repository Rookout/deployment-examples, pull requests merged in 2018-09, with the labels that each got.

#44 fixed broken api
  java-aws-lambda/README.md
  java-aws-lambda/build.gradle
  java-aws-lambda/gradle/wrapper/gradle-wrapper.properties
  java-aws-lambda/gradlew
  java-aws-lambda/gradlew.bat
  java-aws-lambda/settings.gradle
  java-aws-lambda/src/main/java/TestLambda/TestLambda.java
Labels: bug, enhancement

#45 refined gradle example
  java-gradle/Makefile
  java-gradle/README.md
  java-gradle/build.gradle
Labels: DeployEnforcer/MergeOnceApproved, enhancement

#46 Java aws lambda maven
  java-aws-lambda-maven/README.md
  java-aws-lambda-maven/jar-with-dependencies.xml
  java-aws-lambda-maven/pom.xml
  java-aws-lambda-maven/src/main/java/TestLambda/TestLambda.java
Labels: enhancement

#47 Fix readme and format source code
  java-aws-lambda-maven/README.md
  java-aws-lambda-maven/src/main/java/TestLambda/TestLambda.java
Labels: enhancement

#48 Fix make file
  java-gradle/Makefile
Labels: enhancement

#49 Add limits to kubernetes
  python-kubernetes/README.md
  python-kubernetes/agent-deployment.yaml
Labels: enhancement

#50 Fix app engine readme
  node-app-engine-flex/README.md
Labels: enhancement

#51 added docker example for flask and global rule
  python-flask/Dockerfile
  python-flask/README.md
  python-flask/flask_rookout.py
  python-flask/requirements.txt
Labels: bug
