Repository Rookout/deployment-examples, pull requests merged in 2019-02, with the labels that each got.

#87 RK-717 - Python sanic example
  python-sanic/Dockerfile
  python-sanic/Jenkinsfile
  python-sanic/README.md
  python-sanic/requirements.txt
  python-sanic/sanic_rookout.py
Labels: DeployEnforcer/MergeOnceApproved

#83 RK-1127 - Adding maven api
  java-maven/maven-agent/Dockerfile
  java-maven/maven-agent/Jenkinsfile
  java-maven/maven-agent/README.md
  java-maven/maven-agent/pom.xml
  java-maven/maven-agent/src/main/java/com/rookout/HelloWorld.java
  java-maven/maven-api/Dockerfile
  java-maven/maven-api/README.md
  java-maven/maven-api/pom.xml
  java-maven/maven-api/src/main/java/com/rookout/HelloWorld.java
Labels: DeployEnforcer/MergeOnceApproved

#89 RK-1355 - Update serverless build instructions in deployment examples
  java-aws-elasticbeanstalk/README.md
  java-aws-lambda-maven/README.md
  java-aws-lambda/README.md
  java-dropwizard/README.md
  java-gradle/java-agent/README.md
  java-gradle/java-api/README.md
  java-groovy/README.md
  java-maven/maven-agent/README.md
  java-maven/maven-api/README.md
  java-play-framework/README.md
  node-app-engine-flex/README.md
  node-aws-lambda/README.md
  node-electron/README.md
  node-serverless-cross-platform/README.md
  python-aws-chalice/Readme.md
  python-aws-lambda/README.md
  python-aws-serverlessframework/README.md
  python-flask/README.md
  python-kubernetes/rookout-service/README.md
  python-kubernetes/with-agent/README.md
  python-sanic/README.md
Labels: DeployEnforcer/MergeOnceApproved, enhancement

#90 Refresh python flask deployment example RK-368
  python-flask/README.md
  python-flask/flask_rookout.py
  python-flask/requirements.txt
Labels: DeployEnforcer/MergeOnceApproved

#91 RK-1640 - Fix flask test
  python-flask/Jenkinsfile
Labels: DeployEnforcer/MergeOnceApproved, bug
