Repository Rookout/deployment-examples, pull requests merged in 2019-03, with the labels that each got.

#92 RK-1730 PySpark deployment example
  python-django/README.md
  python-sanic/README.md
  python-spark/Dockerfile
  python-spark/Jenkinsfile
  python-spark/README.md
  python-spark/example.py
  python-spark/requirements.txt
  python-spark/sample-data.csv
Labels: DeployEnforcer/MergeOnceApproved

#93 RK-698 - Aws regression test
  .gitignore
  .rookout
  java-aws-lambda/gradlew
  java-gradle/java-api/Dockerfile
  node-aws-lambda/Dockerfile
  node-aws-lambda/Jenkinsfile
  node-aws-lambda/awsTest.sh
  node-aws-lambda/package-lock.json
  python-aws-chalice/Dockerfile
  python-aws-chalice/Jenkinsfile
  python-aws-chalice/runTest.sh
  python-aws-lambda/Dockerfile
  python-aws-lambda/Jenkinsfile
  python-aws-lambda/awsTest.sh
  python-kubernetes/rookout-service/README.md
  python-kubernetes/with-agent/README.md
Labels: DeployEnforcer/MergeOnceApproved, enhancement

#94 RK-1760: Added Tomcat Servlet WAR deployment example
  java-tomcat-war-maven/Dockerfile
  java-tomcat-war-maven/Jenkinsfile
  java-tomcat-war-maven/README.md
  java-tomcat-war-maven/SampleLib/pom.xml
  java-tomcat-war-maven/SampleLib/src/main/java/com/rookout/samplelib/SampleLib.java
  java-tomcat-war-maven/sample/pom.xml
  java-tomcat-war-maven/sample/src/main/java/com/rookout/HelloServlet.java
  java-tomcat-war-maven/sample/src/main/webapp/WEB-INF/web.xml
Labels: DeployEnforcer/MergeOnceApproved

#95 RK-1717 - java-aws-elasticbeanstalk tests
  java-aws-elasticbeanstalk/.ebextensions/00_rookout.config
  java-aws-elasticbeanstalk/.ebextensions/rook.config
  java-aws-elasticbeanstalk/.gitignore
  java-aws-elasticbeanstalk/Dockerfile
  java-aws-elasticbeanstalk/Jenkinsfile
  java-aws-elasticbeanstalk/README.md
  java-aws-elasticbeanstalk/runTest.sh
  java-tomcat-aws-elasticbeanstalk/.ebextensions/00-rookout-agent.config
  java-tomcat-aws-elasticbeanstalk/README.md
  java-tomcat-aws-elasticbeanstalk/eb-tomcat-helloworld/src/.ebextensions/00-rookout-agent.config
  java-tomcat-aws-elasticbeanstalk/eb-tomcat-helloworld/src/.ebextensions/01-rook-tomcat.config
  node-aws-elasticbeanstalk/README.md
Labels: DeployEnforcer/MergeOnceApproved, enhancement

#96 Fix git clone in python spark example
  python-spark/README.md
Labels: DeployEnforcer/MergeOnceApproved

#100 RK-1873: Updated deployment example for Spark with limitations
  python-spark/Jenkinsfile
  python-spark/README.md
  python-spark/example.py
  python-spark/example_executor_module.py
Labels: DeployEnforcer/MergeOnceApproved

#101 RK-1873: Add --py-files argument so that example_executor_module is uploaded
  python-spark/Jenkinsfile
Labels: DeployEnforcer/MergeOnceApproved

#102 RK-1873: Spark example improvements #2
  python-spark/Dockerfile
  python-spark/Jenkinsfile
  python-spark/README.md
Labels: DeployEnforcer/MergeOnceApproved

#106 RK-1927 - Add uuid version instead of time
  java-aws-elasticbeanstalk/runTest.sh
Labels: DeployEnforcer/MergeOnceApproved, enhancement

#103 RK-1905 - Java tomcat elastic test
  java-tomcat-aws-elasticbeanstalk/.ebextensions/01-rook-tomcat.config
  java-tomcat-aws-elasticbeanstalk/.ebextensions/logging.config
  java-tomcat-aws-elasticbeanstalk/.ebextensions/xray.config
  java-tomcat-aws-elasticbeanstalk/README.md
  java-tomcat-aws-elasticbeanstalk/eb-tomcat-helloworld/.ebextensions/logging.config
  java-tomcat-aws-elasticbeanstalk/eb-tomcat-helloworld/.ebextensions/xray.config
  java-tomcat-aws-elasticbeanstalk/eb-tomcat-helloworld/.gitignore
  java-tomcat-aws-elasticbeanstalk/eb-tomcat-helloworld/Dockerfile
  java-tomcat-aws-elasticbeanstalk/eb-tomcat-helloworld/Jenkinsfile
  java-tomcat-aws-elasticbeanstalk/eb-tomcat-helloworld/META-INF/MANIFEST.MF
  java-tomcat-aws-elasticbeanstalk/eb-tomcat-helloworld/Makefile
  java-tomcat-aws-elasticbeanstalk/eb-tomcat-helloworld/WEB-INF/classes/META-INF/LICENSE.txt
  java-tomcat-aws-elasticbeanstalk/eb-tomcat-helloworld/WEB-INF/classes/META-INF/MANIFEST.MF
  java-tomcat-aws-elasticbeanstalk/eb-tomcat-helloworld/WEB-INF/classes/META-INF/NOTICE.txt
  java-tomcat-aws-elasticbeanstalk/eb-tomcat-helloworld/WEB-INF/classes/org/example/AWSXRayServlet.class
  java-tomcat-aws-elasticbeanstalk/eb-tomcat-helloworld/WEB-INF/classes/org/example/AWSXRayServletContext.class
  java-tomcat-aws-elasticbeanstalk/eb-tomcat-helloworld/WEB-INF/classes/org/example/ConditionalAWSXRayServletFilter.class
  java-tomcat-aws-elasticbeanstalk/eb-tomcat-helloworld/WEB-INF/lib/aws-java-sdk-core-1.11.67.jar
  java-tomcat-aws-elasticbeanstalk/eb-tomcat-helloworld/WEB-INF/lib/aws-java-sdk-kms-1.11.67.jar
  java-tomcat-aws-elasticbeanstalk/eb-tomcat-helloworld/WEB-INF/lib/aws-java-sdk-s3-1.11.67.jar
  java-tomcat-aws-elasticbeanstalk/eb-tomcat-helloworld/WEB-INF/lib/aws-xray-recorder-sdk-aws-sdk-1.0.5-beta.jar
  java-tomcat-aws-elasticbeanstalk/eb-tomcat-helloworld/WEB-INF/lib/aws-xray-recorder-sdk-core-1.0.5-beta.jar
  java-tomcat-aws-elasticbeanstalk/eb-tomcat-helloworld/WEB-INF/lib/commons-beanutils-1.9.2.jar
  java-tomcat-aws-elasticbeanstalk/eb-tomcat-helloworld/WEB-INF/lib/commons-codec-1.9.jar
  java-tomcat-aws-elasticbeanstalk/eb-tomcat-helloworld/WEB-INF/lib/commons-collections-3.2.2.jar
  java-tomcat-aws-elasticbeanstalk/eb-tomcat-helloworld/WEB-INF/lib/commons-digester-1.8.1.jar
  java-tomcat-aws-elasticbeanstalk/eb-tomcat-helloworld/WEB-INF/lib/commons-digester3-3.2-bin.jar
  java-tomcat-aws-elasticbeanstalk/eb-tomcat-helloworld/WEB-INF/lib/commons-logging-1.1.3.jar
  java-tomcat-aws-elasticbeanstalk/eb-tomcat-helloworld/WEB-INF/lib/commons-validator-1.5.1.jar
  java-tomcat-aws-elasticbeanstalk/eb-tomcat-helloworld/WEB-INF/lib/httpclient-4.5.2.jar
  java-tomcat-aws-elasticbeanstalk/eb-tomcat-helloworld/WEB-INF/lib/httpcore-4.4.4.jar
  java-tomcat-aws-elasticbeanstalk/eb-tomcat-helloworld/WEB-INF/lib/ion-java-1.0.1.jar
  java-tomcat-aws-elasticbeanstalk/eb-tomcat-helloworld/WEB-INF/lib/jackson-annotations-2.6.0.jar
  java-tomcat-aws-elasticbeanstalk/eb-tomcat-helloworld/WEB-INF/lib/jackson-core-2.6.6.jar
  java-tomcat-aws-elasticbeanstalk/eb-tomcat-helloworld/WEB-INF/lib/jackson-databind-2.6.6.jar
  java-tomcat-aws-elasticbeanstalk/eb-tomcat-helloworld/WEB-INF/lib/jackson-dataformat-cbor-2.6.6.jar
  java-tomcat-aws-elasticbeanstalk/eb-tomcat-helloworld/WEB-INF/lib/jmespath-java-1.0.jar
  java-tomcat-aws-elasticbeanstalk/eb-tomcat-helloworld/WEB-INF/lib/joda-time-2.8.1.jar
  java-tomcat-aws-elasticbeanstalk/eb-tomcat-helloworld/WEB-INF/web.xml
  java-tomcat-aws-elasticbeanstalk/eb-tomcat-helloworld/build.sh
  java-tomcat-aws-elasticbeanstalk/eb-tomcat-helloworld/cron.yaml
  java-tomcat-aws-elasticbeanstalk/eb-tomcat-helloworld/index.jsp
  java-tomcat-aws-elasticbeanstalk/eb-tomcat-helloworld/runTest.sh
  java-tomcat-aws-elasticbeanstalk/eb-tomcat-helloworld/scheduled.jsp
  java-tomcat-aws-elasticbeanstalk/eb-tomcat-helloworld/src/.ebextensions/01-rook-tomcat.config
  java-tomcat-aws-elasticbeanstalk/eb-tomcat-helloworld/src/AWSXRayServlet.java
  java-tomcat-aws-elasticbeanstalk/eb-tomcat-helloworld/src/AWSXRayServletContext.java
  java-tomcat-aws-elasticbeanstalk/eb-tomcat-helloworld/src/ConditionalAWSXRayServletFilter.java
  java-tomcat-aws-elasticbeanstalk/eb-tomcat-helloworld/src/WEB-INF/lib/jsp-api.jar
  java-tomcat-aws-elasticbeanstalk/eb-tomcat-helloworld/src/WEB-INF/lib/servlet-api.jar
  java-tomcat-aws-elasticbeanstalk/eb-tomcat-helloworld/src/WEB-INF/web.xml
  java-tomcat-aws-elasticbeanstalk/eb-tomcat-helloworld/src/com/rookout/web/HelloWorld.java
Labels: DeployEnforcer/MergeOnceApproved, enhancement

#105 RK-1911 - Node elastic test
  node-aws-elasticbeanstalk/.ebextensions/00-rookout-agent.config
  node-aws-elasticbeanstalk/.ebextensions/env_options.config
  node-aws-elasticbeanstalk/.ebextensions/logging.config
  node-aws-elasticbeanstalk/README.md
  node-aws-elasticbeanstalk/node-example/.ebextensions/00-rookout-agent.config
  node-aws-elasticbeanstalk/node-example/.ebextensions/01-start.config
  node-aws-elasticbeanstalk/node-example/.ebextensions/env_options.config
  node-aws-elasticbeanstalk/node-example/.ebextensions/logging.config
  node-aws-elasticbeanstalk/node-example/.gitignore
  node-aws-elasticbeanstalk/node-example/Dockerfile
  node-aws-elasticbeanstalk/node-example/Jenkinsfile
  node-aws-elasticbeanstalk/node-example/app.js
  node-aws-elasticbeanstalk/node-example/cron.yaml
  node-aws-elasticbeanstalk/node-example/index.html
  node-aws-elasticbeanstalk/node-example/package-lock.json
  node-aws-elasticbeanstalk/node-example/package.json
  node-aws-elasticbeanstalk/node-example/runTest.sh
  node-aws-elasticbeanstalk/node-example/server.js
Labels: DeployEnforcer/MergeOnceApproved, enhancement

#107 RK-1973 - Add dockerfile.test check
  .jenkins/Jenkinsfile
Labels: enhancement

#108 Add chalice delete insted of lambda delete
  python-aws-chalice/runTest.sh
Labels: DeployEnforcer/MergeOnceApproved, enhancement

#109 RK-1949 , RK-1999 - Manuel/node serverless test
  node-serverless-cross-platform/.dockerignore
  node-serverless-cross-platform/.dockerignroe
  node-serverless-cross-platform/.gitignore
  node-serverless-cross-platform/Dockerfile.test
  node-serverless-cross-platform/Jenkinsfile
  node-serverless-cross-platform/index.js
  node-serverless-cross-platform/runTest.sh
  node-serverless-cross-platform/serverless.yml
Labels: DeployEnforcer/MergeOnceApproved

#110 RK-1948 - Manuel/python serverless test
  python-aws-serverlessframework/Dockerfile
  python-aws-serverlessframework/Jenkinsfile
  python-aws-serverlessframework/README.md
  python-aws-serverlessframework/package.json
  python-aws-serverlessframework/serverless.yml
  python-aws-serverlessframework/testEnvs.sh
Labels: DeployEnforcer/MergeOnceApproved, enhancement
