Repository Rookout/deployment-examples, pull requests merged in 2019-01, with the labels that each got.

#79 RK-364 example of using serverless on non-linux machine
  node-serverless-cross-platform/.dockerignroe
  node-serverless-cross-platform/Dockerfile
  node-serverless-cross-platform/README.md
  node-serverless-cross-platform/index.js
  node-serverless-cross-platform/package-lock.json
  node-serverless-cross-platform/package.json
  node-serverless-cross-platform/serverless.yml
Labels: enhancement

#77 RK-1060: Multi-stage build for Wildfly - also builds the WAR
  java-wildfly-docker/README.md
  java-wildfly-docker/helloworld/.gitignore
  java-wildfly-docker/helloworld/Dockerfile
  java-wildfly-docker/helloworld/README.md
  java-wildfly-docker/helloworld/pom.xml
  java-wildfly-docker/helloworld/rookout-conf/standalone.conf
  java-wildfly-docker/helloworld/rookout/LOGS_GO_HERE
  java-wildfly-docker/helloworld/src/main/java/org/jboss/as/quickstarts/helloworld/HelloService.java
  java-wildfly-docker/helloworld/src/main/java/org/jboss/as/quickstarts/helloworld/HelloWorldServlet.java
  java-wildfly-docker/helloworld/src/main/webapp/WEB-INF/beans.xml
  java-wildfly-docker/helloworld/src/main/webapp/index.html
Labels: DeployEnforcer/MergeOnceApproved

#75 RK-662 - Fix and update node-electron deployment example
  .jenkins/Jenkinsfile
  node-electron/README.md
  node-electron/package-lock.json
  node-electron/package.json
Labels: DeployEnforcer/MergeOnceApproved, enhancement

#84 RK-1199 - Fix typescript
  node-typescript/Jenkinsfile
Labels: DeployEnforcer/MergeOnceApproved, bug
